In [63]:
import requests
import os
from dotenv import load_dotenv

In [64]:
load_dotenv()

True

In [65]:
ticker = "AAPL"
API_KEY = os.getenv('ALPHA_VANTAGE_API_KEY')

In [66]:
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={ticker}&apikey={API_KEY}'
r = requests.get(url)
data = r.json()

print(data)

{'Information': 'Thank you for using Alpha Vantage! Our standard API rate limit is 25 requests per day. Please subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly remove all daily rate limits.'}

In [49]:
data

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'AAPL',
  '3. Last Refreshed': '2025-02-24',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2025-02-24': {'1. open': '244.9250',
   '2. high': '248.8600',
   '3. low': '244.4200',
   '4. close': '247.1000',
   '5. volume': '51326396'},
  '2025-02-21': {'1. open': '245.9500',
   '2. high': '248.6900',
   '3. low': '245.2200',
   '4. close': '245.5500',
   '5. volume': '53197431'},
  '2025-02-20': {'1. open': '244.9400',
   '2. high': '246.7800',
   '3. low': '244.2900',
   '4. close': '245.8300',
   '5. volume': '32316907'},
  '2025-02-19': {'1. open': '244.6600',
   '2. high': '246.0100',
   '3. low': '243.1604',
   '4. close': '244.8700',
   '5. volume': '32204215'},
  '2025-02-18': {'1. open': '244.1500',
   '2. high': '245.1800',
   '3. low': '241.8400',
   '4. close': '244.4700',
   '5. volume': '48822491'},
  '2025-02-14': {'1. open': '241.2500',
   '2. high': '245.5500',
   '3. low': '240.9900',
   '4. close': '244.6000',
   '5. volume': '40896227'},
  '2025-02-13': {'1. open': '236.9100',
   '2. high': '242.3399',
   '3. low': '235.5700',
   '4. close': '241.5300',
   '5. volume': '53614054'},
  '2025-02-12': {'1. open': '231.2000',
   '2. high': '236.9600',
   '3. low': '230.6800',
   '4. close': '236.8700',
   '5. volume': '45243292'},
  '2025-02-11': {'1. open': '228.2000',
   '2. high': '235.2300',
   '3. low': '228.1300',
   '4. close': '232.6200',
   '5. volume': '53718362'},
  '2025-02-10': {'1. open': '229.5700',
   '2. high': '230.5850',
   '3. low': '227.2000',
   '4. close': '227.6500',
   '5. volume': '33115645'},
  '2025-02-07': {'1. open': '232.6000',
   '2. high': '234.0000',
   '3. low': '227.2600',
   '4. close': '227.6300',
   '5. volume': '39707224'},
  '2025-02-06': {'1. open': '231.2850',
   '2. high': '233.8000',
   '3. low': '230.4250',
   '4. close': '233.2200',
   '5. volume': '29925349'},
  '2025-02-05': {'1. open': '228.5300',
   '2. high': '232.6700',
   '3. low': '228.2700',
   '4. close': '232.4700',
   '5. volume': '39664989'},
  '2025-02-04': {'1. open': '227.2500',
   '2. high': '233.1300',
   '3. low': '226.6500',
   '4. close': '232.8000',
   '5. volume': '45067301'},
  '2025-02-03': {'1. open': '229.9900',
   '2. high': '231.8300',
   '3. low': '225.7000',
   '4. close': '228.0100',
   '5. volume': '73063301'},
  '2025-01-31': {'1. open': '247.1900',
   '2. high': '247.1900',
   '3. low': '233.4400',
   '4. close': '236.0000',
   '5. volume': '101075128'},
  '2025-01-30': {'1. open': '238.6650',
   '2. high': '240.7900',
   '3. low': '237.2100',
   '4. close': '237.5900',
   '5. volume': '55658279'},
  '2025-01-29': {'1. open': '234.1200',
   '2. high': '239.8550',
   '3. low': '234.0100',
   '4. close': '239.3600',
   '5. volume': '45486100'},
  '2025-01-28': {'1. open': '230.8500',
   '2. high': '240.1900',
   '3. low': '230.8100',
   '4. close': '238.2600',
   '5. volume': '75707569'},
  '2025-01-27': {'1. open': '224.0200',
   '2. high': '232.1500',
   '3. low': '223.9800',
   '4. close': '229.8600',
   '5. volume': '94863418'},
  '2025-01-24': {'1. open': '224.7800',
   '2. high': '225.6300',
   '3. low': '221.4100',
   '4. close': '222.7800',
   '5. volume': '54697907'},
  '2025-01-23': {'1. open': '224.7400',
   '2. high': '227.0300',
   '3. low': '222.3000',
   '4. close': '223.6600',
   '5. volume': '60234760'},
  '2025-01-22': {'1. open': '219.7900',
   '2. high': '224.1200',
   '3. low': '219.7900',
   '4. close': '223.8300',
   '5. volume': '64126500'},
  '2025-01-21': {'1. open': '224.0000',
   '2. high': '224.4200',
   '3. low': '219.3800',
   '4. close': '222.6400',
   '5. volume': '98070429'},
  '2025-01-17': {'1. open': '232.1150',
   '2. high': '232.2900',
   '3. low': '228.4800',
   '4. close': '229.9800',
   '5. volume': '68488301'},
  '2025-01-16': {'1. open': '237.3500',
   '2. high': '238.0100',
   '3. low': '228.0300',
   '4. close': '228.2600',
   '5. volume': '71759052'},
  '2025-01-15': {'1. open': '234.6350',
   '2. high': '238.9600',
   '3. low': '234.4300',
   '4. close': '237.8700',
   '5. volume': '39831969'},
  '2025-01-14': {'1. open': '234.7500',
   '2. high': '236.1200',
   '3. low': '232.4720',
   '4. close': '233.2800',
   '5. volume': '39435294'},
  '2025-01-13': {'1. open': '233.5300',
   '2. high': '234.6700',
   '3. low': '229.7200',
   '4. close': '234.4000',
   '5. volume': '49630725'},
  '2025-01-10': {'1. open': '240.0100',
   '2. high': '240.1600',
   '3. low': '233.0000',
   '4. close': '236.8500',
   '5. volume': '61710856'},
  '2025-01-08': {'1. open': '241.9200',
   '2. high': '243.7123',
   '3. low': '240.0500',
   '4. close': '242.7000',
   '5. volume': '37628940'},
  '2025-01-07': {'1. open': '242.9800',
   '2. high': '245.5500',
   '3. low': '241.3500',
   '4. close': '242.2100',
   '5. volume': '40855960'},
  '2025-01-06': {'1. open': '244.3100',
   '2. high': '247.3300',
   '3. low': '243.2000',
   '4. close': '245.0000',
   '5. volume': '45045571'},
  '2025-01-03': {'1. open': '243.3600',
   '2. high': '244.1800',
   '3. low': '241.8900',
   '4. close': '243.3600',
   '5. volume': '40244114'},
  '2025-01-02': {'1. open': '248.9300',
   '2. high': '249.1000',
   '3. low': '241.8201',
   '4. close': '243.8500',
   '5. volume': '55740731'},
  '2024-12-31': {'1. open': '252.4400',
   '2. high': '253.2800',
   '3. low': '249.4300',
   '4. close': '250.4200',
   '5. volume': '39480718'},
  '2024-12-30': {'1. open': '252.2300',
   '2. high': '253.5000',
   '3. low': '250.7500',
   '4. close': '252.2000',
   '5. volume': '35557542'},
  '2024-12-27': {'1. open': '257.8300',
   '2. high': '258.7000',
   '3. low': '253.0600',
   '4. close': '255.5900',
   '5. volume': '42355321'},
  '2024-12-26': {'1. open': '258.1900',
   '2. high': '260.1000',
   '3. low': '257.6300',
   '4. close': '259.0200',
   '5. volume': '27262983'},
  '2024-12-24': {'1. open': '255.4900',
   '2. high': '258.2100',
   '3. low': '255.2900',
   '4. close': '258.2000',
   '5. volume': '23234705'},
  '2024-12-23': {'1. open': '254.7700',
   '2. high': '255.6500',
   '3. low': '253.4500',
   '4. close': '255.2700',
   '5. volume': '40858774'},
  '2024-12-20': {'1. open': '248.0400',
   '2. high': '255.0000',
   '3. low': '245.6900',
   '4. close': '254.4900',
   '5. volume': '147495267'},
  '2024-12-19': {'1. open': '247.5000',
   '2. high': '252.0000',
   '3. low': '247.0949',
   '4. close': '249.7900',
   '5. volume': '60882264'},
  '2024-12-18': {'1. open': '252.1600',
   '2. high': '254.2800',
   '3. low': '247.7400',
   '4. close': '248.0500',
   '5. volume': '56774101'},
  '2024-12-17': {'1. open': '250.0800',
   '2. high': '253.8300',
   '3. low': '249.7800',
   '4. close': '253.4800',
   '5. volume': '51356360'},
  '2024-12-16': {'1. open': '247.9900',
   '2. high': '251.3800',
   '3. low': '247.6500',
   '4. close': '251.0400',
   '5. volume': '51694753'},
  '2024-12-13': {'1. open': '247.8150',
   '2. high': '249.2902',
   '3. low': '246.2400',
   '4. close': '248.1300',
   '5. volume': '33155290'},
  '2024-12-12': {'1. open': '246.8900',
   '2. high': '248.7400',
   '3. low': '245.6800',
   '4. close': '247.9600',
   '5. volume': '32777532'},
  '2024-12-11': {'1. open': '247.9600',
   '2. high': '250.8000',
   '3. low': '246.2601',
   '4. close': '246.4900',
   '5. volume': '45205814'},
  '2024-12-10': {'1. open': '246.8900',
   '2. high': '248.2100',
   '3. low': '245.3400',
   '4. close': '247.7700',
   '5. volume': '36914806'},
  '2024-12-09': {'1. open': '241.8300',
   '2. high': '247.2400',
   '3. low': '241.7500',
   '4. close': '246.7500',
   '5. volume': '44649232'},
  '2024-12-06': {'1. open': '242.9050',
   '2. high': '244.6300',
   '3. low': '242.0800',
   '4. close': '242.8400',
   '5. volume': '36870619'},
  '2024-12-05': {'1. open': '243.9900',
   '2. high': '244.5400',
   '3. low': '242.1300',
   '4. close': '243.0400',
   '5. volume': '40033878'},
  '2024-12-04': {'1. open': '242.8700',
   '2. high': '244.1100',
   '3. low': '241.2500',
   '4. close': '243.0100',
   '5. volume': '44383935'},
  '2024-12-03': {'1. open': '239.8100',
   '2. high': '242.7600',
   '3. low': '238.9000',
   '4. close': '242.6500',
   '5. volume': '38861017'},
  '2024-12-02': {'1. open': '237.2700',
   '2. high': '240.7900',
   '3. low': '237.1600',
   '4. close': '239.5900',
   '5. volume': '48137103'},
  '2024-11-29': {'1. open': '234.8100',
   '2. high': '237.8100',
   '3. low': '233.9700',
   '4. close': '237.3300',
   '5. volume': '28481377'},
  '2024-11-27': {'1. open': '234.4650',
   '2. high': '235.6900',
   '3. low': '233.8101',
   '4. close': '234.9300',
   '5. volume': '33498439'},
  '2024-11-26': {'1. open': '233.3300',
   '2. high': '235.5700',
   '3. low': '233.3300',
   '4. close': '235.0600',
   '5. volume': '45986189'},
  '2024-11-25': {'1. open': '231.4600',
   '2. high': '233.2450',
   '3. low': '229.7400',
   '4. close': '232.8700',
   '5. volume': '90152832'},
  '2024-11-22': {'1. open': '228.0600',
   '2. high': '230.7199',
   '3. low': '228.0600',
   '4. close': '229.8700',
   '5. volume': '38168252'},
  '2024-11-21': {'1. open': '228.8800',
   '2. high': '230.1550',
   '3. low': '225.7103',
   '4. close': '228.5200',
   '5. volume': '42108327'},
  '2024-11-20': {'1. open': '228.0600',
   '2. high': '229.9300',
   '3. low': '225.8900',
   '4. close': '229.0000',
   '5. volume': '35169566'},
  '2024-11-19': {'1. open': '226.9800',
   '2. high': '230.1600',
   '3. low': '226.6600',
   '4. close': '228.2800',
   '5. volume': '36211774'},
  '2024-11-18': {'1. open': '225.2500',
   '2. high': '229.7400',
   '3. low': '225.1700',
   '4. close': '228.0200',
   '5. volume': '44686020'},
  '2024-11-15': {'1. open': '226.4000',
   '2. high': '226.9200',
   '3. low': '224.2700',
   '4. close': '225.0000',
   '5. volume': '47923696'},
  '2024-11-14': {'1. open': '225.0200',
   '2. high': '228.8700',
   '3. low': '225.0000',
   '4. close': '228.2200',
   '5. volume': '44923941'},
  '2024-11-13': {'1. open': '224.0100',
   '2. high': '226.6500',
   '3. low': '222.7600',
   '4. close': '225.1200',
   '5. volume': '48566217'},
  '2024-11-12': {'1. open': '224.5500',
   '2. high': '225.5900',
   '3. low': '223.3550',
   '4. close': '224.2300',
   '5. volume': '40398299'},
  '2024-11-11': {'1. open': '225.0000',
   '2. high': '225.7000',
   '3. low': '221.5000',
   '4. close': '224.2300',
   '5. volume': '42005602'},
  '2024-11-08': {'1. open': '227.1700',
   '2. high': '228.6600',
   '3. low': '226.4050',
   '4. close': '226.9600',
   '5. volume': '38328824'},
  '2024-11-07': {'1. open': '224.6250',
   '2. high': '227.8750',
   '3. low': '224.5700',
   '4. close': '227.4800',
   '5. volume': '42137691'},
  '2024-11-06': {'1. open': '222.6100',
   '2. high': '226.0650',
   '3. low': '221.1900',
   '4. close': '222.7200',
   '5. volume': '54561121'},
  '2024-11-05': {'1. open': '221.7950',
   '2. high': '223.9500',
   '3. low': '221.1400',
   '4. close': '223.4500',
   '5. volume': '28111338'},
  '2024-11-04': {'1. open': '220.9900',
   '2. high': '222.7900',
   '3. low': '219.7100',
   '4. close': '222.0100',
   '5. volume': '44944468'},
  '2024-11-01': {'1. open': '220.9650',
   '2. high': '225.3500',
   '3. low': '220.2700',
   '4. close': '222.9100',
   '5. volume': '65276741'},
  '2024-10-31': {'1. open': '229.3400',
   '2. high': '229.8300',
   '3. low': '225.3700',
   '4. close': '225.9100',
   '5. volume': '64370086'},
  '2024-10-30': {'1. open': '232.6100',
   '2. high': '233.4700',
   '3. low': '229.5500',
   '4. close': '230.1000',
   '5. volume': '47070907'},
  '2024-10-29': {'1. open': '233.1000',
   '2. high': '234.3250',
   '3. low': '232.3200',
   '4. close': '233.6700',
   '5. volume': '35417247'},
  '2024-10-28': {'1. open': '233.3200',
   '2. high': '234.7300',
   '3. low': '232.5500',
   '4. close': '233.4000',
   '5. volume': '36087134'},
  '2024-10-25': {'1. open': '229.7400',
   '2. high': '233.2200',
   '3. low': '229.5700',
   '4. close': '231.4100',
   '5. volume': '38802304'},
  '2024-10-24': {'1. open': '229.9800',
   '2. high': '230.8200',
   '3. low': '228.4100',
   '4. close': '230.5700',
   '5. volume': '31109503'},
  '2024-10-23': {'1. open': '234.0800',
   '2. high': '235.1440',
   '3. low': '227.7600',
   '4. close': '230.7600',
   '5. volume': '52286979'},
  '2024-10-22': {'1. open': '233.8850',
   '2. high': '236.2200',
   '3. low': '232.6000',
   '4. close': '235.8600',
   '5. volume': '38846578'},
  '2024-10-21': {'1. open': '234.4500',
   '2. high': '236.8500',
   '3. low': '234.4500',
   '4. close': '236.4800',
   '5. volume': '36254470'},
  '2024-10-18': {'1. open': '236.1800',
   '2. high': '236.1800',
   '3. low': '234.0100',
   '4. close': '235.0000',
   '5. volume': '46431472'},
  '2024-10-17': {'1. open': '233.4300',
   '2. high': '233.8500',
   '3. low': '230.5200',
   '4. close': '232.1500',
   '5. volume': '32993810'},
  '2024-10-16': {'1. open': '231.6000',
   '2. high': '232.1200',
   '3. low': '229.8400',
   '4. close': '231.7800',
   '5. volume': '34082240'},
  '2024-10-15': {'1. open': '233.6100',
   '2. high': '237.4900',
   '3. low': '232.3700',
   '4. close': '233.8500',
   '5. volume': '64751367'},
  '2024-10-14': {'1. open': '228.7000',
   '2. high': '231.7300',
   '3. low': '228.6000',
   '4. close': '231.3000',
   '5. volume': '39882085'},
  '2024-10-11': {'1. open': '229.3000',
   '2. high': '229.4100',
   '3. low': '227.3400',
   '4. close': '227.5500',
   '5. volume': '31759188'},
  '2024-10-10': {'1. open': '227.7800',
   '2. high': '229.5000',
   '3. low': '227.1700',
   '4. close': '229.0400',
   '5. volume': '28183544'},
  '2024-10-09': {'1. open': '225.2300',
   '2. high': '229.7500',
   '3. low': '224.8300',
   '4. close': '229.5400',
   '5. volume': '33591091'},
  '2024-10-08': {'1. open': '224.3000',
   '2. high': '225.9800',
   '3. low': '223.2500',
   '4. close': '225.7700',
   '5. volume': '31855693'},
  '2024-10-07': {'1. open': '224.5000',
   '2. high': '225.6900',
   '3. low': '221.3300',
   '4. close': '221.6900',
   '5. volume': '39505354'},
  '2024-10-04': {'1. open': '227.9000',
   '2. high': '228.0000',
   '3. low': '224.1300',
   '4. close': '226.8000',
   '5. volume': '37345098'},
  '2024-10-03': {'1. open': '225.1400',
   '2. high': '226.8050',
   '3. low': '223.3200',
   '4. close': '225.6700',
   '5. volume': '34044158'},
  '2024-10-02': {'1. open': '225.8900',
   '2. high': '227.3700',
   '3. low': '223.0200',
   '4. close': '226.7800',
   '5. volume': '32880605'},
  '2024-10-01': {'1. open': '229.5200',
   '2. high': '229.6500',
   '3. low': '223.7400',
   '4. close': '226.2100',
   '5. volume': '63285048'},
  '2024-09-30': {'1. open': '230.0400',
   '2. high': '233.0000',
   '3. low': '229.6500',
   '4. close': '233.0000',
   '5. volume': '54793391'}}}

In [50]:
type(data['Time Series (Daily)'])

dict

In [51]:
data['Time Series (Daily)']['2024-12-18']

{'1. open': '252.1600',
 '2. high': '254.2800',
 '3. low': '247.7400',
 '4. close': '248.0500',
 '5. volume': '56774101'}

In [52]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={ticker}&interval=60min&apikey={API_KEY}'
r = requests.get(url)
data = r.json()

print(data)

{'Meta Data': {'1. Information': 'Intraday (60min) open, high, low, close prices and volume', '2. Symbol': 'AAPL', '3. Last Refreshed': '2025-02-24 19:00:00', '4. Interval': '60min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (60min)': {'2025-02-24 19:00:00': {'1. open': '247.6100', '2. high': '248.4500', '3. low': '247.5500', '4. close': '248.0600', '5. volume': '45649'}, '2025-02-24 18:00:00': {'1. open': '247.7700', '2. high': '248.0500', '3. low': '247.4000', '4. close': '247.6000', '5. volume': '72912'}, '2025-02-24 17:00:00': {'1. open': '247.8910', '2. high': '265.1391', '3. low': '247.1000', '4. close': '247.7800', '5. volume': '64103'}, '2025-02-24 16:00:00': {'1. open': '247.2200', '2. high': '248.2000', '3. low': '236.8500', '4. close': '247.8900', '5. volume': '18577671'}, '2025-02-24 15:00:00': {'1. open': '247.9650', '2. high': '248.2300', '3. low': '246.8200', '4. close': '247.2300', '5. volume': '6807237'}, '2025-02-24 14:00:00': {'1. open': '247.9800', '2. high': '248.8000', '3. low': '247.4300', '4. close': '247.9800', '5. volume': '4424448'}, '2025-02-24 13:00:00': {'1. open': '247.2700', '2. high': '248.2200', '3. low': '247.2200', '4. close': '247.9800', '5. volume': '3100347'}, '2025-02-24 12:00:00': {'1. open': '248.0000', '2. high': '248.2800', '3. low': '247.2700', '4. close': '247.2700', '5. volume': '2581892'}, '2025-02-24 11:00:00': {'1. open': '247.2200', '2. high': '248.3200', '3. low': '246.2700', '4. close': '248.0000', '5. volume': '4959229'}, '2025-02-24 10:00:00': {'1. open': '248.0800', '2. high': '248.8600', '3. low': '244.8241', '4. close': '247.2250', '5. volume': '9076535'}, '2025-02-24 09:00:00': {'1. open': '244.3300', '2. high': '248.1400', '3. low': '243.0700', '4. close': '248.0650', '5. volume': '7387893'}, '2025-02-24 08:00:00': {'1. open': '243.9000', '2. high': '246.0000', '3. low': '241.5738', '4. close': '244.3700', '5. volume': '292062'}, '2025-02-24 07:00:00': {'1. open': '243.8600', '2. high': '244.4000', '3. low': '243.4600', '4. close': '243.8800', '5. volume': '172185'}, '2025-02-24 06:00:00': {'1. open': '245.2100', '2. high': '245.2700', '3. low': '241.5500', '4. close': '243.8000', '5. volume': '340006'}, '2025-02-24 05:00:00': {'1. open': '245.2600', '2. high': '245.2900', '3. low': '245.1000', '4. close': '245.2000', '5. volume': '17861'}, '2025-02-24 04:00:00': {'1. open': '245.3900', '2. high': '245.9000', '3. low': '245.0000', '4. close': '245.2200', '5. volume': '32697'}, '2025-02-21 19:00:00': {'1. open': '245.1800', '2. high': '245.2867', '3. low': '245.0000', '4. close': '245.0300', '5. volume': '25955'}, '2025-02-21 18:00:00': {'1. open': '245.2800', '2. high': '245.5500', '3. low': '233.1900', '4. close': '245.1800', '5. volume': '53596'}, '2025-02-21 17:00:00': {'1. open': '245.3000', '2. high': '245.5500', '3. low': '245.0000', '4. close': '245.2000', '5. volume': '55564'}, '2025-02-21 16:00:00': {'1. open': '245.5900', '2. high': '247.1367', '3. low': '245.3000', '4. close': '245.3000', '5. volume': '15723056'}, '2025-02-21 15:00:00': {'1. open': '245.9100', '2. high': '246.0900', '3. low': '245.3300', '4. close': '245.5900', '5. volume': '9671954'}, '2025-02-21 14:00:00': {'1. open': '247.7500', '2. high': '247.8700', '3. low': '245.6320', '4. close': '245.9200', '5. volume': '5756020'}, '2025-02-21 13:00:00': {'1. open': '248.4500', '2. high': '248.4900', '3. low': '247.0400', '4. close': '247.7400', '5. volume': '6251065'}, '2025-02-21 12:00:00': {'1. open': '247.0200', '2. high': '248.6900', '3. low': '246.9000', '4. close': '248.4300', '5. volume': '5251304'}, '2025-02-21 11:00:00': {'1. open': '245.8150', '2. high': '247.5000', '3. low': '245.8150', '4. close': '247.0150', '5. volume': '6574468'}, '2025-02-21 10:00:00': {'1. open': '245.6400', '2. high': '246.0100', '3. low': '245.2200', '4. close': '245.8300', '5. volume': '3766935'}, '2025-02-21 09:00:00': {'1. open': '245.9400', '2. high': '246.9400', '3. low': '245.2500', '4. close': '245.6900', '5. volume': '6217521'}, '2025-02-21 08:00:00': {'1. open': '245.6325', '2. high': '246.2000', '3. low': '244.8400', '4. close': '245.8900', '5. volume': '90254'}, '2025-02-21 07:00:00': {'1. open': '245.4000', '2. high': '245.8300', '3. low': '245.3600', '4. close': '245.7500', '5. volume': '17797'}, '2025-02-21 06:00:00': {'1. open': '245.3500', '2. high': '245.4500', '3. low': '245.3000', '4. close': '245.4000', '5. volume': '4687'}, '2025-02-21 05:00:00': {'1. open': '245.4000', '2. high': '245.4000', '3. low': '245.2400', '4. close': '245.3100', '5. volume': '9848'}, '2025-02-21 04:00:00': {'1. open': '246.0000', '2. high': '246.0000', '3. low': '245.1200', '4. close': '245.3600', '5. volume': '12480'}, '2025-02-20 19:00:00': {'1. open': '245.6500', '2. high': '245.7500', '3. low': '245.5700', '4. close': '245.6000', '5. volume': '7499'}, '2025-02-20 18:00:00': {'1. open': '245.6500', '2. high': '245.8300', '3. low': '245.5000', '4. close': '245.6900', '5. volume': '36527'}, '2025-02-20 17:00:00': {'1. open': '245.7200', '2. high': '251.7307', '3. low': '234.0006', '4. close': '245.6700', '5. volume': '1147732'}, '2025-02-20 16:00:00': {'1. open': '245.8600', '2. high': '245.8600', '3. low': '245.6000', '4. close': '245.7200', '5. volume': '10284514'}, '2025-02-20 15:00:00': {'1. open': '245.3300', '2. high': '246.0000', '3. low': '245.2724', '4. close': '245.8600', '5. volume': '4357865'}, '2025-02-20 14:00:00': {'1. open': '245.3300', '2. high': '245.7500', '3. low': '244.8500', '4. close': '245.3350', '5. volume': '2008507'}, '2025-02-20 13:00:00': {'1. open': '245.3690', '2. high': '245.8178', '3. low': '245.0200', '4. close': '245.3506', '5. volume': '2066070'}, '2025-02-20 12:00:00': {'1. open': '245.2650', '2. high': '246.4600', '3. low': '245.0300', '4. close': '245.3600', '5. volume': '2819029'}, '2025-02-20 11:00:00': {'1. open': '245.1100', '2. high': '246.7000', '3. low': '245.0800', '4. close': '245.2750', '5. volume': '5034401'}, '2025-02-20 10:00:00': {'1. open': '244.9000', '2. high': '245.3539', '3. low': '244.2900', '4. close': '245.0700', '5. volume': '3902573'}, '2025-02-20 09:00:00': {'1. open': '243.7967', '2. high': '246.7800', '3. low': '243.7600', '4. close': '244.9000', '5. volume': '4542419'}, '2025-02-20 08:00:00': {'1. open': '244.1262', '2. high': '244.9020', '3. low': '243.5000', '4. close': '243.7800', '5. volume': '148481'}, '2025-02-20 07:00:00': {'1. open': '243.8200', '2. high': '244.6100', '3. low': '243.8200', '4. close': '244.4600', '5. volume': '17999'}, '2025-02-20 06:00:00': {'1. open': '244.1200', '2. high': '244.1600', '3. low': '243.8000', '4. close': '243.8300', '5. volume': '10681'}, '2025-02-20 05:00:00': {'1. open': '244.1000', '2. high': '244.2400', '3. low': '244.0000', '4. close': '244.1300', '5. volume': '11782'}, '2025-02-20 04:00:00': {'1. open': '244.4000', '2. high': '244.4000', '3. low': '243.7700', '4. close': '244.1300', '5. volume': '29494'}, '2025-02-19 19:00:00': {'1. open': '244.6500', '2. high': '258.4298', '3. low': '236.4454', '4. close': '244.8000', '5. volume': '11829'}, '2025-02-19 18:00:00': {'1. open': '244.3700', '2. high': '244.9800', '3. low': '244.3000', '4. close': '244.7200', '5. volume': '18184'}, '2025-02-19 17:00:00': {'1. open': '244.5600', '2. high': '244.6000', '3. low': '244.2500', '4. close': '244.3300', '5. volume': '20025'}, '2025-02-19 16:00:00': {'1. open': '244.8900', '2. high': '245.0400', '3. low': '243.6750', '4. close': '244.5800', '5. volume': '11734755'}, '2025-02-19 15:00:00': {'1. open': '244.8400', '2. high': '245.1800', '3. low': '244.5350', '4. close': '244.8900', '5. volume': '4551739'}, '2025-02-19 14:00:00': {'1. open': '244.7400', '2. high': '245.0800', '3. low': '244.2200', '4. close': '244.8350', '5. volume': '2254718'}, '2025-02-19 13:00:00': {'1. open': '244.7300', '2. high': '245.1899', '3. low': '244.2300', '4. close': '244.7300', '5. volume': '1825641'}, '2025-02-19 12:00:00': {'1. open': '244.7900', '2. high': '245.6600', '3. low': '244.6273', '4. close': '244.7200', '5. volume': '2598159'}, '2025-02-19 11:00:00': {'1. open': '243.4100', '2. high': '244.9499', '3. low': '243.1604', '4. close': '244.7800', '5. volume': '3620150'}, '2025-02-19 10:00:00': {'1. open': '245.0700', '2. high': '245.5800', '3. low': '243.2600', '4. close': '243.4200', '5. volume': '4171289'}, '2025-02-19 09:00:00': {'1. open': '244.1200', '2. high': '246.0100', '3. low': '243.7300', '4. close': '245.0700', '5. volume': '3963073'}, '2025-02-19 08:00:00': {'1. open': '244.6490', '2. high': '245.2500', '3. low': '233.2200', '4. close': '244.1100', '5. volume': '1730094'}, '2025-02-19 07:00:00': {'1. open': '243.8400', '2. high': '244.3400', '3. low': '243.8200', '4. close': '244.2300', '5. volume': '19431'}, '2025-02-19 06:00:00': {'1. open': '244.1100', '2. high': '244.1800', '3. low': '243.7400', '4. close': '243.8200', '5. volume': '16297'}, '2025-02-19 05:00:00': {'1. open': '244.6000', '2. high': '244.6600', '3. low': '244.0000', '4. close': '244.0400', '5. volume': '15630'}, '2025-02-19 04:00:00': {'1. open': '245.2100', '2. high': '245.5500', '3. low': '244.5200', '4. close': '244.5600', '5. volume': '22025'}, '2025-02-18 19:00:00': {'1. open': '244.9500', '2. high': '245.4500', '3. low': '244.8000', '4. close': '245.4000', '5. volume': '39742'}, '2025-02-18 18:00:00': {'1. open': '244.5800', '2. high': '244.9900', '3. low': '244.5800', '4. close': '244.9012', '5. volume': '25642'}, '2025-02-18 17:00:00': {'1. open': '244.5300', '2. high': '247.6583', '3. low': '227.4311', '4. close': '244.5500', '5. volume': '598794'}, '2025-02-18 16:00:00': {'1. open': '244.4700', '2. high': '244.7500', '3. low': '243.7517', '4. close': '244.5500', '5. volume': '24210718'}, '2025-02-18 15:00:00': {'1. open': '243.6989', '2. high': '244.9530', '3. low': '243.1500', '4. close': '244.4600', '5. volume': '6176542'}, '2025-02-18 14:00:00': {'1. open': '242.6100', '2. high': '243.8350', '3. low': '241.8400', '4. close': '243.6950', '5. volume': '3285269'}, '2025-02-18 13:00:00': {'1. open': '243.9700', '2. high': '244.1155', '3. low': '242.3101', '4. close': '242.6200', '5. volume': '3184600'}, '2025-02-18 12:00:00': {'1. open': '244.8950', '2. high': '244.9500', '3. low': '243.9300', '4. close': '243.9750', '5. volume': '2218460'}, '2025-02-18 11:00:00': {'1. open': '244.3300', '2. high': '245.0500', '3. low': '244.2200', '4. close': '244.8900', '5. volume': '3422221'}, '2025-02-18 10:00:00': {'1. open': '244.9840', '2. high': '245.0972', '3. low': '243.8600', '4. close': '244.3300', '5. volume': '4302409'}, '2025-02-18 09:00:00': {'1. open': '244.7300', '2. high': '245.1800', '3. low': '242.8200', '4. close': '244.9300', '5. volume': '6905979'}, '2025-02-18 08:00:00': {'1. open': '244.7500', '2. high': '245.5700', '3. low': '241.3750', '4. close': '244.7500', '5. volume': '1229301'}, '2025-02-18 07:00:00': {'1. open': '244.7400', '2. high': '245.0000', '3. low': '244.6400', '4. close': '244.9500', '5. volume': '55745'}, '2025-02-18 06:00:00': {'1. open': '244.9400', '2. high': '245.2000', '3. low': '244.6400', '4. close': '244.7100', '5. volume': '26349'}, '2025-02-18 05:00:00': {'1. open': '244.9400', '2. high': '244.9600', '3. low': '244.7900', '4. close': '244.9400', '5. volume': '14860'}, '2025-02-18 04:00:00': {'1. open': '243.8900', '2. high': '245.8800', '3. low': '243.8900', '4. close': '244.9400', '5. volume': '38642'}, '2025-02-14 19:00:00': {'1. open': '244.5075', '2. high': '244.8000', '3. low': '244.5000', '4. close': '244.6400', '5. volume': '8777'}, '2025-02-14 18:00:00': {'1. open': '244.5800', '2. high': '244.7925', '3. low': '244.2500', '4. close': '244.6700', '5. volume': '54023'}, '2025-02-14 17:00:00': {'1. open': '244.7900', '2. high': '244.7900', '3. low': '243.2133', '4. close': '244.4900', '5. volume': '560697'}, '2025-02-14 16:00:00': {'1. open': '244.5700', '2. high': '245.0000', '3. low': '244.2976', '4. close': '244.8100', '5. volume': '12811327'}, '2025-02-14 15:00:00': {'1. open': '244.2650', '2. high': '245.5500', '3. low': '243.9100', '4. close': '244.5700', '5. volume': '6329664'}, '2025-02-14 14:00:00': {'1. open': '244.1602', '2. high': '244.3700', '3. low': '243.9400', '4. close': '244.2683', '5. volume': '1987317'}, '2025-02-14 13:00:00': {'1. open': '243.9150', '2. high': '244.5400', '3. low': '243.8000', '4. close': '244.1600', '5. volume': '1927290'}, '2025-02-14 12:00:00': {'1. open': '244.3700', '2. high': '244.5300', '3. low': '243.3400', '4. close': '243.9100', '5. volume': '3785102'}, '2025-02-14 11:00:00': {'1. open': '244.2800', '2. high': '244.4500', '3. low': '243.1600', '4. close': '244.3800', '5. volume': '3739684'}, '2025-02-14 10:00:00': {'1. open': '244.3100', '2. high': '245.0500', '3. low': '243.1800', '4. close': '244.2800', '5. volume': '7464197'}, '2025-02-14 09:00:00': {'1. open': '240.8300', '2. high': '244.4200', '3. low': '236.8600', '4. close': '244.3200', '5. volume': '6417866'}, '2025-02-14 08:00:00': {'1. open': '241.7335', '2. high': '242.4600', '3. low': '240.4400', '4. close': '240.8200', '5. volume': '258220'}, '2025-02-14 07:00:00': {'1. open': '240.7200', '2. high': '241.0200', '3. low': '240.6400', '4. close': '240.9500', '5. volume': '37473'}, '2025-02-14 06:00:00': {'1. open': '241.5100', '2. high': '241.7100', '3. low': '240.4400', '4. close': '240.6900', '5. volume': '65008'}, '2025-02-14 05:00:00': {'1. open': '241.0600', '2. high': '241.5900', '3. low': '240.6200', '4. close': '241.5100', '5. volume': '41617'}, '2025-02-14 04:00:00': {'1. open': '242.0000', '2. high': '242.0000', '3. low': '241.0200', '4. close': '241.0700', '5. volume': '49889'}, '2025-02-13 19:00:00': {'1. open': '241.3200', '2. high': '241.6200', '3. low': '241.2000', '4. close': '241.3800', '5. volume': '57939'}, '2025-02-13 18:00:00': {'1. open': '241.2000', '2. high': '241.4975', '3. low': '241.1800', '4. close': '241.3100', '5. volume': '18098'}, '2025-02-13 17:00:00': {'1. open': '241.3200', '2. high': '252.5918', '3. low': '241.0900', '4. close': '241.2900', '5. volume': '1275270'}, '2025-02-13 16:00:00': {'1. open': '241.5200', '2. high': '242.0000', '3. low': '241.2100', '4. close': '241.3199', '5. volume': '25964313'}}}

In [53]:
type(data['Time Series (60min)'])

dict

In [54]:
len(data['Time Series (60min)'])

100

In [55]:
data['Time Series (60min)']

{'2025-02-24 19:00:00': {'1. open': '247.6100',
  '2. high': '248.4500',
  '3. low': '247.5500',
  '4. close': '248.0600',
  '5. volume': '45649'},
 '2025-02-24 18:00:00': {'1. open': '247.7700',
  '2. high': '248.0500',
  '3. low': '247.4000',
  '4. close': '247.6000',
  '5. volume': '72912'},
 '2025-02-24 17:00:00': {'1. open': '247.8910',
  '2. high': '265.1391',
  '3. low': '247.1000',
  '4. close': '247.7800',
  '5. volume': '64103'},
 '2025-02-24 16:00:00': {'1. open': '247.2200',
  '2. high': '248.2000',
  '3. low': '236.8500',
  '4. close': '247.8900',
  '5. volume': '18577671'},
 '2025-02-24 15:00:00': {'1. open': '247.9650',
  '2. high': '248.2300',
  '3. low': '246.8200',
  '4. close': '247.2300',
  '5. volume': '6807237'},
 '2025-02-24 14:00:00': {'1. open': '247.9800',
  '2. high': '248.8000',
  '3. low': '247.4300',
  '4. close': '247.9800',
  '5. volume': '4424448'},
 '2025-02-24 13:00:00': {'1. open': '247.2700',
  '2. high': '248.2200',
  '3. low': '247.2200',
  '4. close': '247.9800',
  '5. volume': '3100347'},
 '2025-02-24 12:00:00': {'1. open': '248.0000',
  '2. high': '248.2800',
  '3. low': '247.2700',
  '4. close': '247.2700',
  '5. volume': '2581892'},
 '2025-02-24 11:00:00': {'1. open': '247.2200',
  '2. high': '248.3200',
  '3. low': '246.2700',
  '4. close': '248.0000',
  '5. volume': '4959229'},
 '2025-02-24 10:00:00': {'1. open': '248.0800',
  '2. high': '248.8600',
  '3. low': '244.8241',
  '4. close': '247.2250',
  '5. volume': '9076535'},
 '2025-02-24 09:00:00': {'1. open': '244.3300',
  '2. high': '248.1400',
  '3. low': '243.0700',
  '4. close': '248.0650',
  '5. volume': '7387893'},
 '2025-02-24 08:00:00': {'1. open': '243.9000',
  '2. high': '246.0000',
  '3. low': '241.5738',
  '4. close': '244.3700',
  '5. volume': '292062'},
 '2025-02-24 07:00:00': {'1. open': '243.8600',
  '2. high': '244.4000',
  '3. low': '243.4600',
  '4. close': '243.8800',
  '5. volume': '172185'},
 '2025-02-24 06:00:00': {'1. open': '245.2100',
  '2. high': '245.2700',
  '3. low': '241.5500',
  '4. close': '243.8000',
  '5. volume': '340006'},
 '2025-02-24 05:00:00': {'1. open': '245.2600',
  '2. high': '245.2900',
  '3. low': '245.1000',
  '4. close': '245.2000',
  '5. volume': '17861'},
 '2025-02-24 04:00:00': {'1. open': '245.3900',
  '2. high': '245.9000',
  '3. low': '245.0000',
  '4. close': '245.2200',
  '5. volume': '32697'},
 '2025-02-21 19:00:00': {'1. open': '245.1800',
  '2. high': '245.2867',
  '3. low': '245.0000',
  '4. close': '245.0300',
  '5. volume': '25955'},
 '2025-02-21 18:00:00': {'1. open': '245.2800',
  '2. high': '245.5500',
  '3. low': '233.1900',
  '4. close': '245.1800',
  '5. volume': '53596'},
 '2025-02-21 17:00:00': {'1. open': '245.3000',
  '2. high': '245.5500',
  '3. low': '245.0000',
  '4. close': '245.2000',
  '5. volume': '55564'},
 '2025-02-21 16:00:00': {'1. open': '245.5900',
  '2. high': '247.1367',
  '3. low': '245.3000',
  '4. close': '245.3000',
  '5. volume': '15723056'},
 '2025-02-21 15:00:00': {'1. open': '245.9100',
  '2. high': '246.0900',
  '3. low': '245.3300',
  '4. close': '245.5900',
  '5. volume': '9671954'},
 '2025-02-21 14:00:00': {'1. open': '247.7500',
  '2. high': '247.8700',
  '3. low': '245.6320',
  '4. close': '245.9200',
  '5. volume': '5756020'},
 '2025-02-21 13:00:00': {'1. open': '248.4500',
  '2. high': '248.4900',
  '3. low': '247.0400',
  '4. close': '247.7400',
  '5. volume': '6251065'},
 '2025-02-21 12:00:00': {'1. open': '247.0200',
  '2. high': '248.6900',
  '3. low': '246.9000',
  '4. close': '248.4300',
  '5. volume': '5251304'},
 '2025-02-21 11:00:00': {'1. open': '245.8150',
  '2. high': '247.5000',
  '3. low': '245.8150',
  '4. close': '247.0150',
  '5. volume': '6574468'},
 '2025-02-21 10:00:00': {'1. open': '245.6400',
  '2. high': '246.0100',
  '3. low': '245.2200',
  '4. close': '245.8300',
  '5. volume': '3766935'},
 '2025-02-21 09:00:00': {'1. open': '245.9400',
  '2. high': '246.9400',
  '3. low': '245.2500',
  '4. close': '245.6900',
  '5. volume': '6217521'},
 '2025-02-21 08:00:00': {'1. open': '245.6325',
  '2. high': '246.2000',
  '3. low': '244.8400',
  '4. close': '245.8900',
  '5. volume': '90254'},
 '2025-02-21 07:00:00': {'1. open': '245.4000',
  '2. high': '245.8300',
  '3. low': '245.3600',
  '4. close': '245.7500',
  '5. volume': '17797'},
 '2025-02-21 06:00:00': {'1. open': '245.3500',
  '2. high': '245.4500',
  '3. low': '245.3000',
  '4. close': '245.4000',
  '5. volume': '4687'},
 '2025-02-21 05:00:00': {'1. open': '245.4000',
  '2. high': '245.4000',
  '3. low': '245.2400',
  '4. close': '245.3100',
  '5. volume': '9848'},
 '2025-02-21 04:00:00': {'1. open': '246.0000',
  '2. high': '246.0000',
  '3. low': '245.1200',
  '4. close': '245.3600',
  '5. volume': '12480'},
 '2025-02-20 19:00:00': {'1. open': '245.6500',
  '2. high': '245.7500',
  '3. low': '245.5700',
  '4. close': '245.6000',
  '5. volume': '7499'},
 '2025-02-20 18:00:00': {'1. open': '245.6500',
  '2. high': '245.8300',
  '3. low': '245.5000',
  '4. close': '245.6900',
  '5. volume': '36527'},
 '2025-02-20 17:00:00': {'1. open': '245.7200',
  '2. high': '251.7307',
  '3. low': '234.0006',
  '4. close': '245.6700',
  '5. volume': '1147732'},
 '2025-02-20 16:00:00': {'1. open': '245.8600',
  '2. high': '245.8600',
  '3. low': '245.6000',
  '4. close': '245.7200',
  '5. volume': '10284514'},
 '2025-02-20 15:00:00': {'1. open': '245.3300',
  '2. high': '246.0000',
  '3. low': '245.2724',
  '4. close': '245.8600',
  '5. volume': '4357865'},
 '2025-02-20 14:00:00': {'1. open': '245.3300',
  '2. high': '245.7500',
  '3. low': '244.8500',
  '4. close': '245.3350',
  '5. volume': '2008507'},
 '2025-02-20 13:00:00': {'1. open': '245.3690',
  '2. high': '245.8178',
  '3. low': '245.0200',
  '4. close': '245.3506',
  '5. volume': '2066070'},
 '2025-02-20 12:00:00': {'1. open': '245.2650',
  '2. high': '246.4600',
  '3. low': '245.0300',
  '4. close': '245.3600',
  '5. volume': '2819029'},
 '2025-02-20 11:00:00': {'1. open': '245.1100',
  '2. high': '246.7000',
  '3. low': '245.0800',
  '4. close': '245.2750',
  '5. volume': '5034401'},
 '2025-02-20 10:00:00': {'1. open': '244.9000',
  '2. high': '245.3539',
  '3. low': '244.2900',
  '4. close': '245.0700',
  '5. volume': '3902573'},
 '2025-02-20 09:00:00': {'1. open': '243.7967',
  '2. high': '246.7800',
  '3. low': '243.7600',
  '4. close': '244.9000',
  '5. volume': '4542419'},
 '2025-02-20 08:00:00': {'1. open': '244.1262',
  '2. high': '244.9020',
  '3. low': '243.5000',
  '4. close': '243.7800',
  '5. volume': '148481'},
 '2025-02-20 07:00:00': {'1. open': '243.8200',
  '2. high': '244.6100',
  '3. low': '243.8200',
  '4. close': '244.4600',
  '5. volume': '17999'},
 '2025-02-20 06:00:00': {'1. open': '244.1200',
  '2. high': '244.1600',
  '3. low': '243.8000',
  '4. close': '243.8300',
  '5. volume': '10681'},
 '2025-02-20 05:00:00': {'1. open': '244.1000',
  '2. high': '244.2400',
  '3. low': '244.0000',
  '4. close': '244.1300',
  '5. volume': '11782'},
 '2025-02-20 04:00:00': {'1. open': '244.4000',
  '2. high': '244.4000',
  '3. low': '243.7700',
  '4. close': '244.1300',
  '5. volume': '29494'},
 '2025-02-19 19:00:00': {'1. open': '244.6500',
  '2. high': '258.4298',
  '3. low': '236.4454',
  '4. close': '244.8000',
  '5. volume': '11829'},
 '2025-02-19 18:00:00': {'1. open': '244.3700',
  '2. high': '244.9800',
  '3. low': '244.3000',
  '4. close': '244.7200',
  '5. volume': '18184'},
 '2025-02-19 17:00:00': {'1. open': '244.5600',
  '2. high': '244.6000',
  '3. low': '244.2500',
  '4. close': '244.3300',
  '5. volume': '20025'},
 '2025-02-19 16:00:00': {'1. open': '244.8900',
  '2. high': '245.0400',
  '3. low': '243.6750',
  '4. close': '244.5800',
  '5. volume': '11734755'},
 '2025-02-19 15:00:00': {'1. open': '244.8400',
  '2. high': '245.1800',
  '3. low': '244.5350',
  '4. close': '244.8900',
  '5. volume': '4551739'},
 '2025-02-19 14:00:00': {'1. open': '244.7400',
  '2. high': '245.0800',
  '3. low': '244.2200',
  '4. close': '244.8350',
  '5. volume': '2254718'},
 '2025-02-19 13:00:00': {'1. open': '244.7300',
  '2. high': '245.1899',
  '3. low': '244.2300',
  '4. close': '244.7300',
  '5. volume': '1825641'},
 '2025-02-19 12:00:00': {'1. open': '244.7900',
  '2. high': '245.6600',
  '3. low': '244.6273',
  '4. close': '244.7200',
  '5. volume': '2598159'},
 '2025-02-19 11:00:00': {'1. open': '243.4100',
  '2. high': '244.9499',
  '3. low': '243.1604',
  '4. close': '244.7800',
  '5. volume': '3620150'},
 '2025-02-19 10:00:00': {'1. open': '245.0700',
  '2. high': '245.5800',
  '3. low': '243.2600',
  '4. close': '243.4200',
  '5. volume': '4171289'},
 '2025-02-19 09:00:00': {'1. open': '244.1200',
  '2. high': '246.0100',
  '3. low': '243.7300',
  '4. close': '245.0700',
  '5. volume': '3963073'},
 '2025-02-19 08:00:00': {'1. open': '244.6490',
  '2. high': '245.2500',
  '3. low': '233.2200',
  '4. close': '244.1100',
  '5. volume': '1730094'},
 '2025-02-19 07:00:00': {'1. open': '243.8400',
  '2. high': '244.3400',
  '3. low': '243.8200',
  '4. close': '244.2300',
  '5. volume': '19431'},
 '2025-02-19 06:00:00': {'1. open': '244.1100',
  '2. high': '244.1800',
  '3. low': '243.7400',
  '4. close': '243.8200',
  '5. volume': '16297'},
 '2025-02-19 05:00:00': {'1. open': '244.6000',
  '2. high': '244.6600',
  '3. low': '244.0000',
  '4. close': '244.0400',
  '5. volume': '15630'},
 '2025-02-19 04:00:00': {'1. open': '245.2100',
  '2. high': '245.5500',
  '3. low': '244.5200',
  '4. close': '244.5600',
  '5. volume': '22025'},
 '2025-02-18 19:00:00': {'1. open': '244.9500',
  '2. high': '245.4500',
  '3. low': '244.8000',
  '4. close': '245.4000',
  '5. volume': '39742'},
 '2025-02-18 18:00:00': {'1. open': '244.5800',
  '2. high': '244.9900',
  '3. low': '244.5800',
  '4. close': '244.9012',
  '5. volume': '25642'},
 '2025-02-18 17:00:00': {'1. open': '244.5300',
  '2. high': '247.6583',
  '3. low': '227.4311',
  '4. close': '244.5500',
  '5. volume': '598794'},
 '2025-02-18 16:00:00': {'1. open': '244.4700',
  '2. high': '244.7500',
  '3. low': '243.7517',
  '4. close': '244.5500',
  '5. volume': '24210718'},
 '2025-02-18 15:00:00': {'1. open': '243.6989',
  '2. high': '244.9530',
  '3. low': '243.1500',
  '4. close': '244.4600',
  '5. volume': '6176542'},
 '2025-02-18 14:00:00': {'1. open': '242.6100',
  '2. high': '243.8350',
  '3. low': '241.8400',
  '4. close': '243.6950',
  '5. volume': '3285269'},
 '2025-02-18 13:00:00': {'1. open': '243.9700',
  '2. high': '244.1155',
  '3. low': '242.3101',
  '4. close': '242.6200',
  '5. volume': '3184600'},
 '2025-02-18 12:00:00': {'1. open': '244.8950',
  '2. high': '244.9500',
  '3. low': '243.9300',
  '4. close': '243.9750',
  '5. volume': '2218460'},
 '2025-02-18 11:00:00': {'1. open': '244.3300',
  '2. high': '245.0500',
  '3. low': '244.2200',
  '4. close': '244.8900',
  '5. volume': '3422221'},
 '2025-02-18 10:00:00': {'1. open': '244.9840',
  '2. high': '245.0972',
  '3. low': '243.8600',
  '4. close': '244.3300',
  '5. volume': '4302409'},
 '2025-02-18 09:00:00': {'1. open': '244.7300',
  '2. high': '245.1800',
  '3. low': '242.8200',
  '4. close': '244.9300',
  '5. volume': '6905979'},
 '2025-02-18 08:00:00': {'1. open': '244.7500',
  '2. high': '245.5700',
  '3. low': '241.3750',
  '4. close': '244.7500',
  '5. volume': '1229301'},
 '2025-02-18 07:00:00': {'1. open': '244.7400',
  '2. high': '245.0000',
  '3. low': '244.6400',
  '4. close': '244.9500',
  '5. volume': '55745'},
 '2025-02-18 06:00:00': {'1. open': '244.9400',
  '2. high': '245.2000',
  '3. low': '244.6400',
  '4. close': '244.7100',
  '5. volume': '26349'},
 '2025-02-18 05:00:00': {'1. open': '244.9400',
  '2. high': '244.9600',
  '3. low': '244.7900',
  '4. close': '244.9400',
  '5. volume': '14860'},
 '2025-02-18 04:00:00': {'1. open': '243.8900',
  '2. high': '245.8800',
  '3. low': '243.8900',
  '4. close': '244.9400',
  '5. volume': '38642'},
 '2025-02-14 19:00:00': {'1. open': '244.5075',
  '2. high': '244.8000',
  '3. low': '244.5000',
  '4. close': '244.6400',
  '5. volume': '8777'},
 '2025-02-14 18:00:00': {'1. open': '244.5800',
  '2. high': '244.7925',
  '3. low': '244.2500',
  '4. close': '244.6700',
  '5. volume': '54023'},
 '2025-02-14 17:00:00': {'1. open': '244.7900',
  '2. high': '244.7900',
  '3. low': '243.2133',
  '4. close': '244.4900',
  '5. volume': '560697'},
 '2025-02-14 16:00:00': {'1. open': '244.5700',
  '2. high': '245.0000',
  '3. low': '244.2976',
  '4. close': '244.8100',
  '5. volume': '12811327'},
 '2025-02-14 15:00:00': {'1. open': '244.2650',
  '2. high': '245.5500',
  '3. low': '243.9100',
  '4. close': '244.5700',
  '5. volume': '6329664'},
 '2025-02-14 14:00:00': {'1. open': '244.1602',
  '2. high': '244.3700',
  '3. low': '243.9400',
  '4. close': '244.2683',
  '5. volume': '1987317'},
 '2025-02-14 13:00:00': {'1. open': '243.9150',
  '2. high': '244.5400',
  '3. low': '243.8000',
  '4. close': '244.1600',
  '5. volume': '1927290'},
 '2025-02-14 12:00:00': {'1. open': '244.3700',
  '2. high': '244.5300',
  '3. low': '243.3400',
  '4. close': '243.9100',
  '5. volume': '3785102'},
 '2025-02-14 11:00:00': {'1. open': '244.2800',
  '2. high': '244.4500',
  '3. low': '243.1600',
  '4. close': '244.3800',
  '5. volume': '3739684'},
 '2025-02-14 10:00:00': {'1. open': '244.3100',
  '2. high': '245.0500',
  '3. low': '243.1800',
  '4. close': '244.2800',
  '5. volume': '7464197'},
 '2025-02-14 09:00:00': {'1. open': '240.8300',
  '2. high': '244.4200',
  '3. low': '236.8600',
  '4. close': '244.3200',
  '5. volume': '6417866'},
 '2025-02-14 08:00:00': {'1. open': '241.7335',
  '2. high': '242.4600',
  '3. low': '240.4400',
  '4. close': '240.8200',
  '5. volume': '258220'},
 '2025-02-14 07:00:00': {'1. open': '240.7200',
  '2. high': '241.0200',
  '3. low': '240.6400',
  '4. close': '240.9500',
  '5. volume': '37473'},
 '2025-02-14 06:00:00': {'1. open': '241.5100',
  '2. high': '241.7100',
  '3. low': '240.4400',
  '4. close': '240.6900',
  '5. volume': '65008'},
 '2025-02-14 05:00:00': {'1. open': '241.0600',
  '2. high': '241.5900',
  '3. low': '240.6200',
  '4. close': '241.5100',
  '5. volume': '41617'},
 '2025-02-14 04:00:00': {'1. open': '242.0000',
  '2. high': '242.0000',
  '3. low': '241.0200',
  '4. close': '241.0700',
  '5. volume': '49889'},
 '2025-02-13 19:00:00': {'1. open': '241.3200',
  '2. high': '241.6200',
  '3. low': '241.2000',
  '4. close': '241.3800',
  '5. volume': '57939'},
 '2025-02-13 18:00:00': {'1. open': '241.2000',
  '2. high': '241.4975',
  '3. low': '241.1800',
  '4. close': '241.3100',
  '5. volume': '18098'},
 '2025-02-13 17:00:00': {'1. open': '241.3200',
  '2. high': '252.5918',
  '3. low': '241.0900',
  '4. close': '241.2900',
  '5. volume': '1275270'},
 '2025-02-13 16:00:00': {'1. open': '241.5200',
  '2. high': '242.0000',
  '3. low': '241.2100',
  '4. close': '241.3199',
  '5. volume': '25964313'}}

In [56]:
import pandas as pd
df = pd.DataFrame.from_dict(data['Time Series (60min)'], orient='index')

In [57]:
df

                      1. open   2. high    3. low  4. close 5. volume
2025-02-24 19:00:00  247.6100  248.4500  247.5500  248.0600     45649
2025-02-24 18:00:00  247.7700  248.0500  247.4000  247.6000     72912
2025-02-24 17:00:00  247.8910  265.1391  247.1000  247.7800     64103
2025-02-24 16:00:00  247.2200  248.2000  236.8500  247.8900  18577671
2025-02-24 15:00:00  247.9650  248.2300  246.8200  247.2300   6807237
...                       ...       ...       ...       ...       ...
2025-02-14 04:00:00  242.0000  242.0000  241.0200  241.0700     49889
2025-02-13 19:00:00  241.3200  241.6200  241.2000  241.3800     57939
2025-02-13 18:00:00  241.2000  241.4975  241.1800  241.3100     18098
2025-02-13 17:00:00  241.3200  252.5918  241.0900  241.2900   1275270
2025-02-13 16:00:00  241.5200  242.0000  241.2100  241.3199  25964313

[100 rows x 5 columns]

In [59]:
#change the column names
df.columns = ['open', 'high', 'low', 'close', 'volume']

In [60]:
df['close'] = df['close'].astype(float)
df['daily_returns'] = df['close'].pct_change()
df

,open,high,low,close,volume,daily_returns
2025-02-24 19:00:00,247.6100,248.4500,247.5500,248.0600,45649,NaN
2025-02-24 18:00:00,247.7700,248.0500,247.4000,247.6000,72912,-0.001854
2025-02-24 17:00:00,247.8910,265.1391,247.1000,247.7800,64103,0.000727
2025-02-24 16:00:00,247.2200,248.2000,236.8500,247.8900,18577671,0.000444
2025-02-24 15:00:00,247.9650,248.2300,246.8200,247.2300,6807237,-0.002662
...,...,...,...,...,...,...
2025-02-14 04:00:00,242.0000,242.0000,241.0200,241.0700,49889,-0.001822
2025-02-13 19:00:00,241.3200,241.6200,241.2000,241.3800,57939,0.001286
2025-02-13 18:00:00,241.2000,241.4975,241.1800,241.3100,18098,-0.000290
2025-02-13 17:00:00,241.3200,252.5918,241.0900,241.2900,1275270,-0.000083
2025-02-13 16:00:00,241.5200,242.0000,241.2100,241.3199,25964313,0.000124

In [62]:
#name the index column 
df.index.name = 'timestamp'
df

,open,high,low,close,volume,daily_returns
timestamp,,,,,,
2025-02-24 19:00:00,247.6100,248.4500,247.5500,248.0600,45649,NaN
2025-02-24 18:00:00,247.7700,248.0500,247.4000,247.6000,72912,-0.001854
2025-02-24 17:00:00,247.8910,265.1391,247.1000,247.7800,64103,0.000727
2025-02-24 16:00:00,247.2200,248.2000,236.8500,247.8900,18577671,0.000444
2025-02-24 15:00:00,247.9650,248.2300,246.8200,247.2300,6807237,-0.002662
...,...,...,...,...,...,...
2025-02-14 04:00:00,242.0000,242.0000,241.0200,241.0700,49889,-0.001822
2025-02-13 19:00:00,241.3200,241.6200,241.2000,241.3800,57939,0.001286
2025-02-13 18:00:00,241.2000,241.4975,241.1800,241.3100,18098,-0.000290
2025-02-13 17:00:00,241.3200,252.5918,241.0900,241.2900,1275270,-0.000083
2025-02-13 16:00:00,241.5200,242.0000,241.2100,241.3199,25964313,0.000124